import { AIModel, SafetyProfile } from '../types';

export const INDUSTRY_AVERAGE: SafetyProfile = {
  nonToxicity: 76,
  nonStereotype: 73,
  advRobustness: 72,
  oodRobustness: 65,
  advDemoRobustness: 74,
  privacy: 70,
  ethics: 78,
  fairness: 71,
};

export const MOCK_MODELS: AIModel[] = [
  {
    id: 'claude-3-5-sonnet-ailuminate',
    rank: 1,
    name: 'Claude 3.5 Sonnet (20241022)',
    developer: 'Anthropic',
    type: 'Closed',
    params: 'Неизвестно',
    releaseDate: '2024-10',
    license: 'proprietary',
    aggregateScore: 90.3,
    safetyProfile: {
      nonToxicity: 89.7,
      nonStereotype: 88.5,
      advRobustness: 93.3,
      oodRobustness: 84.0,
      advDemoRobustness: 94.3,
      privacy: 88.0,
      ethics: 94.2,
      fairness: 87.3,
    },
    trend: [88, 88.5, 89, 89.5, 90, 90, 90.3],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 90.3, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'claude-3-5-haiku-ailuminate',
    rank: 2,
    name: 'Claude 3.5 Haiku (20241022)',
    developer: 'Anthropic',
    type: 'Closed',
    params: 'Неизвестно',
    releaseDate: '2024-10',
    license: 'proprietary',
    aggregateScore: 89.7,
    safetyProfile: {
      nonToxicity: 88.7,
      nonStereotype: 87.5,
      advRobustness: 92.3,
      oodRobustness: 83.0,
      advDemoRobustness: 93.3,
      privacy: 87.0,
      ethics: 93.2,
      fairness: 86.3,
    },
    trend: [87, 87.5, 88, 88.5, 89, 89.5, 89.7],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 89.7, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'phi-4-ailuminate',
    rank: 3,
    name: 'Phi 4',
    developer: 'Microsoft',
    type: 'Open',
    params: '14B',
    releaseDate: '2024-12',
    license: 'mit',
    aggregateScore: 88.7,
    safetyProfile: {
      nonToxicity: 88.0,
      nonStereotype: 87.5,
      advRobustness: 90.7,
      oodRobustness: 83.0,
      advDemoRobustness: 91.7,
      privacy: 87.0,
      ethics: 91.4,
      fairness: 86.3,
    },
    trend: [86, 86.5, 87, 87.5, 88, 88.5, 88.7],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 88.7, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'mistral-large-moderated-ailuminate',
    rank: 4,
    name: 'Mistral Large 2402 (Moderated)',
    developer: 'Mistral AI',
    type: 'Closed',
    params: 'Неизвестно',
    releaseDate: '2024-02',
    license: 'proprietary',
    aggregateScore: 88.8,
    safetyProfile: {
      nonToxicity: 88.7,
      nonStereotype: 88.0,
      advRobustness: 91.3,
      oodRobustness: 85.0,
      advDemoRobustness: 92.3,
      privacy: 88.0,
      ethics: 92.0,
      fairness: 87.3,
    },
    trend: [86, 87, 87.5, 88, 88.5, 88.5, 88.8],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 88.8, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'gemini-2-flash-001-ailuminate',
    rank: 5,
    name: 'Gemini 2.0 Flash 001',
    developer: 'Google',
    type: 'Closed',
    params: 'Неизвестно',
    releaseDate: '2025-01',
    license: 'proprietary',
    aggregateScore: 81.1,
    safetyProfile: {
      nonToxicity: 79.7,
      nonStereotype: 79.0,
      advRobustness: 83.3,
      oodRobustness: 74.0,
      advDemoRobustness: 86.0,
      privacy: 78.0,
      ethics: 85.4,
      fairness: 77.7,
    },
    trend: [78, 79, 79.5, 80, 80.5, 81, 81.1],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 81.1, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'gpt-4o-ailuminate',
    rank: 6,
    name: 'GPT-4o',
    developer: 'OpenAI',
    type: 'Closed',
    params: 'Неизвестно',
    releaseDate: '2024-05',
    license: 'proprietary',
    aggregateScore: 80.0,
    safetyProfile: {
      nonToxicity: 78.7,
      nonStereotype: 78.0,
      advRobustness: 82.3,
      oodRobustness: 73.0,
      advDemoRobustness: 84.7,
      privacy: 77.0,
      ethics: 84.2,
      fairness: 76.7,
    },
    trend: [77, 78, 78.5, 79, 79.5, 80, 80.0],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 80.0, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'llama-3-1-405b-instruct-ailuminate',
    rank: 7,
    name: 'Llama 3.1 405B Instruct',
    developer: 'Meta',
    type: 'Open',
    params: '405B',
    releaseDate: '2024-07',
    license: 'llama3.1',
    aggregateScore: 78.8,
    safetyProfile: {
      nonToxicity: 77.7,
      nonStereotype: 77.0,
      advRobustness: 81.0,
      oodRobustness: 72.0,
      advDemoRobustness: 83.3,
      privacy: 76.0,
      ethics: 82.6,
      fairness: 75.7,
    },
    trend: [76, 76.5, 77, 77.5, 78, 78.5, 78.8],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 78.8, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'gemma-2-9b-ailuminate',
    rank: 8,
    name: 'Gemma 2 9B',
    developer: 'Google',
    type: 'Open',
    params: '9B',
    releaseDate: '2024-06',
    license: 'gemma',
    aggregateScore: 86.8,
    safetyProfile: {
      nonToxicity: 86.0,
      nonStereotype: 85.5,
      advRobustness: 88.7,
      oodRobustness: 81.0,
      advDemoRobustness: 90.0,
      privacy: 85.0,
      ethics: 89.8,
      fairness: 84.3,
    },
    trend: [84, 84.5, 85, 85.5, 86, 86.5, 86.8],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 86.8, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'llama-3-3-70b-instruct-ailuminate',
    rank: 9,
    name: 'Llama 3.3 70B Instruct',
    developer: 'Meta',
    type: 'Open',
    params: '70B',
    releaseDate: '2024-12',
    license: 'llama3.3',
    aggregateScore: 59.2,
    safetyProfile: {
      nonToxicity: 58.0,
      nonStereotype: 57.5,
      advRobustness: 61.0,
      oodRobustness: 51.0,
      advDemoRobustness: 65.0,
      privacy: 56.0,
      ethics: 64.0,
      fairness: 55.7,
    },
    trend: [56, 57, 57.5, 58, 58.5, 59, 59.2],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 59.2, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
  {
    id: 'olmo-7b-instruct-ailuminate',
    rank: 10,
    name: 'OLMo 7B 0724 Instruct',
    developer: 'Allen AI',
    type: 'Open',
    params: '7B',
    releaseDate: '2024-07',
    license: 'apache-2.0',
    aggregateScore: 30.0,
    safetyProfile: {
      nonToxicity: 28.3,
      nonStereotype: 28.0,
      advRobustness: 32.0,
      oodRobustness: 21.0,
      advDemoRobustness: 36.7,
      privacy: 27.0,
      ethics: 35.6,
      fairness: 26.0,
    },
    trend: [28, 28.5, 29, 29.5, 29.5, 30, 30.0],
    sources: [
      { source: 'MLCommons AILuminate', metric: 'Средний балл безопасности', score: 30.0, maxScore: 100, link: 'https://ailuminate.mlcommons.org/' },
    ],
  },
];
