import { AIModel, SafetyProfile } from '../types';

export const INDUSTRY_AVERAGE: SafetyProfile = {
  ifeval: 52,
  bbh: 48,
  math: 22,
  gpqa: 34,
  musr: 41,
  mmluPro: 39,
};

export const MOCK_MODELS: AIModel[] = [
  {
    id: 'meta-llama-3-1-70b-instruct',
    rank: 1,
    name: 'Llama 3.1 70B Instruct',
    developer: 'Meta',
    type: 'Open',
    params: '70B',
    releaseDate: '2024-07',
    license: 'llama3',
    aggregateScore: 57.4,
    safetyProfile: {
      ifeval: 63,
      bbh: 54,
      math: 30,
      gpqa: 38,
      musr: 49,
      mmluPro: 50,
    },
    trend: [52, 53, 54, 55, 55, 56, 57.4],
    sources: [
      {
        source: 'Open LLM Leaderboard',
        metric: 'IFEval',
        score: 63,
        maxScore: 100,
      },
    ],
  },
  {
    id: 'qwen2-5-72b-instruct',
    rank: 2,
    name: 'Qwen2.5 72B Instruct',
    developer: 'Qwen',
    type: 'Open',
    params: '72B',
    releaseDate: '2024-09',
    license: 'apache-2.0',
    aggregateScore: 59.1,
    safetyProfile: {
      ifeval: 68,
      bbh: 57,
      math: 28,
      gpqa: 39,
      musr: 52,
      mmluPro: 51,
    },
    trend: [55, 55, 56, 57, 58, 58, 59.1],
    sources: [],
  },
  {
    id: 'mixtral-8x22b-instruct',
    rank: 3,
    name: 'Mixtral 8x22B Instruct',
    developer: 'Mistral AI',
    type: 'Open',
    params: '141B',
    releaseDate: '2024-04',
    license: 'apache-2.0',
    aggregateScore: 54.6,
    safetyProfile: {
      ifeval: 60,
      bbh: 50,
      math: 24,
      gpqa: 33,
      musr: 45,
      mmluPro: 46,
    },
    trend: [50, 50, 51, 52, 53, 54, 54.6],
    sources: [],
  },
  {
    id: 'phi-3-medium',
    rank: 4,
    name: 'Phi-3 Medium',
    developer: 'Microsoft',
    type: 'Open',
    params: '14B',
    releaseDate: '2024-05',
    license: 'mit',
    aggregateScore: 48.3,
    safetyProfile: {
      ifeval: 52,
      bbh: 44,
      math: 19,
      gpqa: 28,
      musr: 37,
      mmluPro: 40,
    },
    trend: [44, 45, 46, 47, 47, 48, 48.3],
    sources: [],
  },
  {
    id: 'openai-gpt-4o',
    rank: 5,
    name: 'GPT-4o',
    developer: 'OpenAI',
    type: 'Closed',
    params: 'Unknown',
    releaseDate: '2024-05',
    license: 'proprietary',
    aggregateScore: 72.4,
    safetyProfile: {
      ifeval: 78,
      bbh: 74,
      math: 55,
      gpqa: 61,
      musr: 66,
      mmluPro: 70,
    },
    trend: [68, 69, 70, 71, 71, 72, 72.4],
    sources: [],
  },
  {
    id: 'anthropic-claude-3-5-sonnet',
    rank: 6,
    name: 'Claude 3.5 Sonnet',
    developer: 'Anthropic',
    type: 'Closed',
    params: 'Unknown',
    releaseDate: '2024-06',
    license: 'proprietary',
    aggregateScore: 73.1,
    safetyProfile: {
      ifeval: 79,
      bbh: 73,
      math: 52,
      gpqa: 60,
      musr: 67,
      mmluPro: 71,
    },
    trend: [69, 70, 70, 71, 72, 72, 73.1],
    sources: [],
  },
  {
    id: 'google-gemini-1-5-pro',
    rank: 7,
    name: 'Gemini 1.5 Pro',
    developer: 'Google',
    type: 'Closed',
    params: 'Unknown',
    releaseDate: '2024-02',
    license: 'proprietary',
    aggregateScore: 70.6,
    safetyProfile: {
      ifeval: 76,
      bbh: 70,
      math: 48,
      gpqa: 57,
      musr: 63,
      mmluPro: 69,
    },
    trend: [66, 67, 68, 69, 69, 70, 70.6],
    sources: [],
  },
];
